[build]
  # This will be run the site build
  command = "yarn deploy"
  # This is the directory is publishing to netlify's CDN
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200